### ISSUE TITLE
java.lang.ClassNotFoundException: jakarta.ws.rs.core.Configuration

### ISSUE THREAD

**Issue by aarepuusepp** [SK-EID/smart-id-java-client#69]
**SpringBoot: 2.7.2
smart-id-java-client: 2.2**

Caused by: java.lang.IllegalStateException: Failed to introspect Class [ee.sk.smartid.SmartIdClient] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@73d16e93]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485)
        at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:267)
        ... 32 common frames omitted
Caused by: java.lang.NoClassDefFoundError: jakarta/ws/rs/core/Configuration
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3325)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2466)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467)
        ... 34 common frames omitted
Caused by: java.lang.ClassNotFoundException: jakarta.ws.rs.core.Configuration
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 38 common frames omitted

**Fix:** requires extra dependency jakarta.ws.rs:jakarta.ws.rs-api to overcome the problem!

**Comment by v3rm0n** [comment]
@jalukse you added "javax.ws.rs" package but the classes referenced are in "jakarta.ws.rs"

**Comment by aasaru** [comment]
If you look at
https://github.com/SK-EID/smart-id-java-client/pull/70/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R70
you see that I added
jakarta.ws.rs

It is also visible from here:
https://github.com/SK-EID/smart-id-java-client/blob/master/pom.xml#L72

**Comment by v3rm0n** [comment]
Ah true. So what I didn't notice is the version mismatch. For some reason it resolves to 2.1.6 in my project and not 3.0.0 as specified and that's why I'm seeing the wrong package.
